- name: "Ensure development tools are installed"
  apt: >
    name={{ item }}
    state=present
  with_items:
    - "build-essential"
    - git
    - curl
  tags:
    - nodejs
    - libs
    - pkgs

- name: "Install updated CA Certificates"
  apt: >
    name=ca-certificates
    state=latest
  tags:
    - nodejs
    - libs
    - pkgs
